#!/usr/bin/env python3
"""SP-1200 12-bit linear DAC staircase for `audioeffects.bitcrusher`.

S1: "The DAC is a standard 12 bit linear device" in complement-offset
binary with zero at 0x800. That is mid-tread round-to-nearest of a
12-bit two's-complement word, not a curve fitted by eye.

Δ = 2^(16 − bits). y = round(x / Δ) · Δ on the int16 grid. The
Waveshaper interpolates the table, so the default 12-bit table is 8193
points — enough duplicate codes that the flats are real (dossier §4).
Drive is not `pre_gain`; Bits swaps the table.

Running this file writes the table between the marker comments in
`lib/audioeffects/bitcrusher.py`. Running it again asserts the
module already holds the generated bytes.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MODULE = os.path.join(ROOT, "lib", "audioeffects", "bitcrusher.py")

BEGIN = "# BEGIN BITCRUSHER_CURVE"
END = "# END BITCRUSHER_CURVE"

#: 12-bit default. The table is read at `x_i = -32768 + 65536*i/(P-1)` --
#: the node's OWN grid (`audioif_shaper.c:217`, `position = (value + 1) *
#: 0.5 * (points - 1)` with `value = sample / 32768`), not `65535*i/(P-1)`.
#: The old spacing was 7.99988 codes against the node's 8, so the table
#: drifted up to a whole code across the span and the staircase's treads
#: came out uneven -- 16 codes wide around zero and 8 further out. That
#: wobble, not the quantizer, was what read as Δ/√12 at 12 bits.
DEFAULT_BITS = 12
POINTS = 8193


def quantize(x, bits):
    """Mid-tread round-to-nearest on the int16 grid. Integer only."""
    if bits >= 16:
        if x > 32767:
            return 32767
        if x < -32768:
            return -32768
        return x
    step = 1 << (16 - bits)
    q = ((x + step // 2) // step) * step
    if q > 32767:
        return 32767
    if q < -32768:
        return -32768
    return q


def points_for(bits):
    if bits >= 16:
        return 1025
    if bits >= 14:
        return 32769
    return POINTS


def table_samples(bits=DEFAULT_BITS, points=None):
    if points is None:
        points = points_for(bits)
    last = points - 1
    if 65536 % last:
        raise ValueError("points - 1 must divide 65536 so the table lands on "
                         "the node's own grid; %d does not" % last)
    out = []
    for i in range(points):
        x = -32768 + (65536 * i) // last
        out.append(quantize(x, bits))
    return out


def table_bytes(bits=DEFAULT_BITS, points=None):
    raw = bytearray()
    for sample in table_samples(bits, points):
        u = sample & 0xFFFF
        raw.append(u & 0xFF)
        raw.append((u >> 8) & 0xFF)
    return bytes(raw)


def _literal(data):
    parts = ["CURVE_BYTES = ("]
    chunk = []
    for index, byte in enumerate(data):
        chunk.append("\\x%02x" % byte)
        if len(chunk) == 16:
            parts.append('    b"%s"' % "".join(chunk))
            chunk = []
    if chunk:
        parts.append('    b"%s"' % "".join(chunk))
    parts.append(")")
    return "\n".join(parts) + "\n"


def _block(data):
    return "%s\n%s%s\n" % (BEGIN, _literal(data), END)


def main(argv):
    data = table_bytes()
    block = _block(data)
    with open(MODULE, "r", encoding="utf-8") as handle:
        text = handle.read()
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0:
        sys.stderr.write("markers missing in %s\n" % MODULE)
        return 2
    stop += len(END)
    current = text[start:stop]
    wanted = block.rstrip("\n")
    if current == wanted:
        sys.stdout.write(
            "bitcrusher_curve: already current (%d bytes, %d points, %d bit)\n"
            % (len(data), POINTS, DEFAULT_BITS))
        return 0
    if "--assert" in argv or "--check" in argv:
        sys.stderr.write("bitcrusher_curve: module does not match generator\n")
        return 1
    text = text[:start] + wanted + text[stop:]
    with open(MODULE, "w", encoding="utf-8") as handle:
        handle.write(text)
    sys.stdout.write("bitcrusher_curve: wrote %d bytes, %d points to %s\n"
                     % (len(data), POINTS, MODULE))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
