#!/usr/bin/env python3
"""1N914 one-sided clipper curve for `audioeffects.rebuilt.exciter`.

Derives one normalised Q15 table from the component values named in
`docs/effects-internal/dossiers/Exciter.md` §1 / S1, not by eye.

S1's harmonic creator is one 1N914 across an op-amp with a 10 K threshold
pot and a 47 K output resistor, clipping one polarity only. The DC table
is the Shockley law in series with Rf on the conducting side and a wire
on the reverse side:

    conducting:  u = y + IS * Rf * (exp(y / (N Vt)) - 1)
    reverse:     y = u

IS and N are the 1N914's typical Shockley pair (the same silicon family
as 1N4148; S1 names 1N914). Rf is resistor 648 = 47 K. The 10 K pot sets
how hard the table is driven; Harmonics is `Waveshaper.pre_gain` into
this one table, never a table rebuilt on a knob move.

0 dBFS ≡ 1.0 V peak. Running this file writes the table between the
marker comments in `lib/audioeffects/rebuilt/exciter.py`. Running it
again asserts the module already holds the generated bytes.
"""
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MODULE = os.path.join(ROOT, "lib", "audioeffects", "rebuilt", "exciter.py")

BEGIN = "# BEGIN EXCITER_CURVE"
END = "# END EXCITER_CURVE"

# S1: 1N914, 47 K output resistor. Typical 1N914 Shockley parameters.
IS = 2.52e-9
N = 1.75
VT = 26e-3
RF = 47000.0
NVT = N * VT
#: Table full-scale in volts so Harmonics +24 dB at 0 dBFS (15.8 V) still
#: indexes inside ±1. Linear reverse conduction stays a wire out to that
#: voltage; the +1 end is the 1N914 in deep conduction (~0.45 V).
UMAX = 16.0
POINTS = 1025


def clip_voltage(u):
    """Newton solve of u = y + IS Rf (exp(y/(N Vt)) - 1) for u >= 0."""
    scale = IS * RF
    if u <= 0.0:
        return u
    y = min(u, 0.7)
    for _ in range(40):
        arg = max(-40.0, min(40.0, y / NVT))
        expo = math.exp(arg)
        f = y + scale * (expo - 1.0) - u
        df = 1.0 + scale * expo / NVT
        step = f / df
        y -= step
        if abs(step) < 1e-12:
            break
    return y


def table_bytes():
    out = []
    last = POINTS - 1
    for i in range(POINTS):
        x = -1.0 + 2.0 * i / last
        u = x * UMAX
        v = clip_voltage(u) if u >= 0.0 else u
        q15 = int(round((v / UMAX) * 32767.0))
        q15 = max(-32768, min(32767, q15))
        out.append(q15)
    raw = bytearray()
    for sample in out:
        u = sample & 0xFFFF
        raw.append(u & 0xFF)
        raw.append((u >> 8) & 0xFF)
    return bytes(raw)


def _literal(data):
    parts = ["CURVE_BYTES = ("]
    chunk = []
    for index, byte in enumerate(data):
        chunk.append("\\x%02x" % byte)
        if len(chunk) == 16:
            parts.append('    b"%s"' % "".join(chunk))
            chunk = []
    if chunk:
        parts.append('    b"%s"' % "".join(chunk))
    parts.append(")")
    return "\n".join(parts) + "\n"


def _block(data):
    return "%s\n%s%s\n" % (BEGIN, _literal(data), END)


def main(argv):
    data = table_bytes()
    block = _block(data)
    with open(MODULE, "r", encoding="utf-8") as handle:
        text = handle.read()
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0:
        sys.stderr.write("markers missing in %s\n" % MODULE)
        return 2
    stop += len(END)
    current = text[start:stop]
    wanted = block.rstrip("\n")
    if current == wanted:
        sys.stdout.write(
            "exciter_curve: already current (%d bytes, %d points)\n"
            % (len(data), POINTS))
        return 0
    if "--assert" in argv or "--check" in argv:
        sys.stderr.write("exciter_curve: module does not match generator\n")
        return 1
    text = text[:start] + wanted + text[stop:]
    with open(MODULE, "w", encoding="utf-8") as handle:
        handle.write(text)
    sys.stdout.write("exciter_curve: wrote %d bytes, %d points to %s\n"
                     % (len(data), POINTS, MODULE))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
