#!/usr/bin/env python3
"""TS808 feedback-diode curve for `audioeffects.overdrive`.

Derives one normalised Q15 table from the circuit values in
`docs/effects-internal/dossiers/Overdrive.md` §1 / S6, not by eye.

Static DC solve of Yeh/Abel/Smith DAFx-07 eq. 22 at dV/dt = 0:

    u = In * R2 = V + 2 * IS * R2 * sinh(V / (N * Vt))

R2 is frozen at Drive maximum (R6 + P1 = 551 kΩ) so Drive is gain into
this one table (`Waveshaper.pre_gain`), never a table rebuilt on a knob
move. 0 dBFS ≡ 1.0 V (dossier §8 Q1). The table maps u / UMAX in ±1 to
V, **normalised to the curve's own extreme so it fills int16**; the volts
that full scale stands for are written out beside it as `CURVE_VOLTS` and
the class carries them in the node's `post_gain`.

Running this file writes the table between the marker comments in
`lib/audioeffects/overdrive.py`. Running it again asserts the
module already holds the generated bytes.
"""
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MODULE = os.path.join(ROOT, "lib", "audioeffects", "overdrive.py")

BEGIN = "# BEGIN OVERDRIVE_CURVE"
END = "# END OVERDRIVE_CURVE"

# S1 / S2 drive network
R6 = 51000.0
P1 = 500000.0
R2_MAX = R6 + P1  # 551 kΩ, Drive maximum
# S6 Nexperia 1N4148, in our models.lib
IS = 4.352e-9
N = 1.906
VT = 26e-3
NVT = N * VT
# Table input full-scale in volts of u = In*R2
UMAX = 3.0
POINTS = 1025

# A table that does not reach the rails throws away the only resolution it
# has, for nothing. The curve is normalised to its own extreme and the
# volts are carried back out in the node's `post_gain`, so this refuses
# anything under 95 % of int16 on the larger side (audiocomponents#77).
FILL_FLOOR = 0.95


def feedback_voltage(u, r2=R2_MAX):
    """Newton solve of u = V + 2 IS R2 sinh(V/(N Vt))."""
    scale = 2.0 * IS * r2
    if scale <= 0:
        return 0.0
    v = NVT * math.asinh(u / scale)
    for _ in range(40):
        arg = max(-40.0, min(40.0, v / NVT))
        sh = math.sinh(arg)
        ch = math.cosh(arg)
        f = v + scale * sh - u
        df = 1.0 + scale * ch / NVT
        step = f / df
        v -= step
        if abs(step) < 1e-12:
            break
    return v


def peak_volts():
    """The clipped voltage at the table's own edge, u = UMAX."""
    return abs(feedback_voltage(UMAX))


def curve_volts():
    """Volts the node reads at the table's full scale.

    The table is normalised to 32767 so both rails land exactly on it and
    the curve stays symmetric; `Waveshaper` divides its entries by 32768.
    The ratio is here rather than in the class so the two cannot drift.
    """
    return peak_volts() * 32768.0 / 32767.0


def table_words():
    """The Q15 table, normalised to its own extreme so it fills int16.

    It used to hold volts directly (v * 32768), which peaked at ±11381 -
    35 % of the range, so every entry was quantised nine times more
    coarsely than it needed to be. `CURVE_VOLTS` carries the scale back
    out in `post_gain`, so the class's level is exactly where it was.
    """
    peak = peak_volts()
    out = []
    last = POINTS - 1
    for i in range(POINTS):
        x = -1.0 + 2.0 * i / last
        v = feedback_voltage(x * UMAX)
        q15 = int(round(v / peak * 32767.0))
        q15 = max(-32768, min(32767, q15))
        out.append(q15)
    return out


def fill(words):
    """How much of int16 the table's larger side uses, 0-1."""
    return max(abs(min(words)), abs(max(words))) / 32767.0


def table_bytes(words=None):
    out = table_words() if words is None else words
    raw = bytearray()
    for sample in out:
        u = sample & 0xFFFF
        raw.append(u & 0xFF)
        raw.append((u >> 8) & 0xFF)
    return bytes(raw)


def _literal(data):
    parts = []
    parts.append("#: Volts at the table's full scale. The table is normalised")
    parts.append("#: to its own extreme so it fills int16 (audiocomponents#77)")
    parts.append("#: and this carries the scale back out in `post_gain`.")
    parts.append("CURVE_VOLTS = %.9f" % curve_volts())
    parts.append("CURVE_BYTES = (")
    chunk = []
    for index, byte in enumerate(data):
        chunk.append("\\x%02x" % byte)
        if len(chunk) == 16:
            parts.append('    b"%s"' % "".join(chunk))
            chunk = []
    if chunk:
        parts.append('    b"%s"' % "".join(chunk))
    parts.append(")")
    return "\n".join(parts) + "\n"


def _block(data):
    return "%s\n%s%s\n" % (BEGIN, _literal(data), END)


def main(argv):
    words = table_words()
    used = fill(words)
    if used < FILL_FLOOR:
        sys.stderr.write(
            "overdrive_curve: the table uses %.1f %% of int16 on its larger "
            "side (floor %.0f %%). Normalise it to the curve's own extreme "
            "and carry the scale in post_gain - audiocomponents#77.\n"
            % (100.0 * used, 100.0 * FILL_FLOOR))
        return 3
    data = table_bytes(words)
    block = _block(data)
    with open(MODULE, "r", encoding="utf-8") as handle:
        text = handle.read()
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0:
        sys.stderr.write("markers missing in %s\n" % MODULE)
        return 2
    stop += len(END)
    current = text[start:stop]
    wanted = block.rstrip("\n")
    if current == wanted:
        sys.stdout.write(
            "overdrive_curve: already current (%d bytes, %d points, "
            "%.2f %% of int16, %.6f V full scale)\n"
            % (len(data), POINTS, 100.0 * used, curve_volts()))
        return 0
    if "--assert" in argv or "--check" in argv:
        sys.stderr.write("overdrive_curve: module does not match generator\n")
        return 1
    text = text[:start] + wanted + text[stop:]
    with open(MODULE, "w", encoding="utf-8") as handle:
        handle.write(text)
    sys.stdout.write("overdrive_curve: wrote %d bytes, %d points to %s\n"
                     % (len(data), POINTS, MODULE))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
