#!/usr/bin/env python3
"""Drive curve for `audioeffects.phaser`.

`Phaser`'s Drive is a cubic soft clip, `y = x - x**3 / 3` over x in ±1 - the
first two terms of the series a JFET's channel follows, and the dossier's
proxy for the transistor living inside the all-pass stage. It is not a
circuit solve; there is nothing to derive here that the line above does not
say.

What there *is* to get right is the scale. The curve peaks at **2/3 by
construction**, so a table holding it directly used 66.7 % of int16 and threw
away half a bit of the only resolution a lookup table has
(audiocomponents#77). It is normalised to its own extreme here, and
`CURVE_SCALE` - which is that 2/3 - is written out beside it so the class can
carry it back in the node's `post_gain` and leave its level exactly where it
was.

Running this file writes the table between the marker comments in
`lib/audioeffects/phaser.py`. `--check` asserts the module already holds the
generated bytes instead of writing them.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MODULE = os.path.join(ROOT, "lib", "audioeffects", "phaser.py")

BEGIN = "# BEGIN PHASER_CURVE"
END = "# END PHASER_CURVE"

#: Points in the table. The `Waveshaper` interpolates between neighbours, so
#: this is the grid Drive is read on; 1024 is what the class shipped with and
#: this change is the normalisation and nothing else.
POINTS = 1024

# A table that does not reach the rails throws away the only resolution it
# has, for nothing. The curve is normalised to its own extreme and the scale
# is carried back out in the node's `post_gain`, so this refuses anything
# under 95 % of int16 on the larger side (audiocomponents#77).
FILL_FLOOR = 0.95


def cubic(x):
    """The soft clip itself, on x in ±1."""
    return x - (x * x * x) / 3.0


def curve_scale():
    """What the table's full scale stands for, as a plain gain.

    `cubic(1.0)` is 2/3 exactly, and the table divides by it. The class
    multiplies it into `Waveshaper.post_gain`, so the two cannot drift.
    """
    return cubic(1.0)


def table_words():
    """The Q15 table, normalised to the curve's own extreme.

    It used to hold `round(y * 32767)` directly, which peaked at ±21845 -
    66.7 % of the range - so every entry was quantised half a bit more
    coarsely than it needed to be. The curve is odd and the grid is
    symmetric, so both rails land exactly on ±32767 and the table stays odd:
    an asymmetric table would write even harmonics into a stage that has
    none.
    """
    peak = curve_scale()
    out = []
    last = POINTS - 1
    for index in range(POINTS):
        x = -1.0 + 2.0 * index / last
        q15 = int(round(cubic(x) / peak * 32767.0))
        out.append(max(-32768, min(32767, q15)))
    return out


def fill(words):
    """How much of int16 the table's larger side uses, 0-1."""
    return max(abs(min(words)), abs(max(words))) / 32767.0


def table_bytes(words=None):
    out = table_words() if words is None else words
    raw = bytearray()
    for sample in out:
        value = sample & 0xFFFF
        raw.append(value & 0xFF)
        raw.append((value >> 8) & 0xFF)
    return bytes(raw)


def _literal(data):
    parts = []
    parts.append("#: What the table's full scale stands for. The curve is")
    parts.append("#: normalised to its own extreme so it fills int16")
    parts.append("#: (audiocomponents#77) and this carries the scale back")
    parts.append("#: out in the shaper's `post_gain`.")
    parts.append("CURVE_SCALE = %.9f" % curve_scale())
    parts.append("CURVE_BYTES = (")
    chunk = []
    for byte in data:
        chunk.append("\\x%02x" % byte)
        if len(chunk) == 16:
            parts.append('    b"%s"' % "".join(chunk))
            chunk = []
    if chunk:
        parts.append('    b"%s"' % "".join(chunk))
    parts.append(")")
    return "\n".join(parts) + "\n"


def _block(data):
    return "%s\n%s%s\n" % (BEGIN, _literal(data), END)


def main(argv):
    words = table_words()
    used = fill(words)
    if used < FILL_FLOOR:
        sys.stderr.write(
            "phaser_curve: the table uses %.1f %% of int16 on its larger "
            "side (floor %.0f %%). Normalise it to the curve's own extreme "
            "and carry the scale in post_gain - audiocomponents#77.\n"
            % (100.0 * used, 100.0 * FILL_FLOOR))
        return 3
    data = table_bytes(words)
    block = _block(data)
    with open(MODULE, "r", encoding="utf-8") as handle:
        text = handle.read()
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0:
        sys.stderr.write("markers missing in %s\n" % MODULE)
        return 2
    stop += len(END)
    current = text[start:stop]
    wanted = block.rstrip("\n")
    if current == wanted:
        sys.stdout.write(
            "phaser_curve: already current (%d bytes, %d points, "
            "%.2f %% of int16, scale %.9f)\n"
            % (len(data), POINTS, 100.0 * used, curve_scale()))
        return 0
    if "--assert" in argv or "--check" in argv:
        sys.stderr.write("phaser_curve: module does not match generator\n")
        return 1
    text = text[:start] + wanted + text[stop:]
    with open(MODULE, "w", encoding="utf-8") as handle:
        handle.write(text)
    sys.stdout.write("phaser_curve: wrote %d bytes, %d points to %s\n"
                     % (len(data), POINTS, MODULE))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
